modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="moreyoyos"
version="${file.jarVersion}"
displayName="More Yoyos Mod"
logoFile="moreyoyos.png"
credits="Thanks for this example mod goes to Java"
authors="thiamine128"
description='''
Adds more yoyos to minecraft!
'''
[[dependencies.yoyos]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yoyos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
