modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
[[mods]]
modId="moreyoyos"
version="${file.jarVersion}"
displayName="More Yoyos Mod"
logoFile="moreyoyos.png"
credits="Thanks for this example mod goes to Java"
authors="thiamine128"
description='''
Adds more yoyos to minecraft 1.19!
'''
[[dependencies.yoyos]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.yoyos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.20)"
    ordering="NONE"
    side="BOTH"
